applied:
  companies:
  - name: Timescale
    date: '2026-02-20'
  - name: GitLab
    date: '2026-02-20'
  - name: Believe
    date: '2026-02-20'
  - name: Elastic
    date: '2026-02-20'
  - name: MongoDB
    date: '2026-02-20'
  - name: MACIF
    date: '2026-02-20'
  - name: Datadog
    date: '2026-02-20'
  - name: Theodo Data & AI
    date: '2026-02-20'
  ids: []
not_interested:
  ids:
  - id: 0d3a41f2f5be
    note: Consultant Product Manager Data - Yield  @ Yield | Studio & Advisory (reloc,
      score 68)
  - id: db68c21c85cc
    note: Consultant.e - Data Product Manager @ Wivoo, a Wavestone company (reloc,
      score 68)
  - id: 6fbb4bf954a5
    note: Product Owner / Product Manager Data (H/ @ Monsieur Guiz (reloc, score 68)
  - id: e24977a3a4e0
    note: Data Product Manager (H/F) | Stage @ Liora (reloc, score 42)
  - id: e49cfa29d7f1
    note: Senior Product Manager - Data Management @ Doctolib (reloc, score 42)
  - id: 0cac004e1b01
    note: Product Manager Data SQL BI IA LLM - Log @ AlumnForce - Alumni Success Platform
      (reloc, score 38)
  - id: f8a6fcc1dadf
    note: Product Manager NoSQL Databases @ Scaleway (reloc, score 58)
  - id: 4f7bcf2b6294
    note: Technical Product Manager - xOps @ Dataiku (reloc, score 68)
  - id: ac06ae84d128
    note: IA Product Manager H/F - CDI @ Converteo (reloc, score 68)
  - id: 673e3ba40164
    note: Consultant.e - AI Product Manager @ Wivoo, a Wavestone company (reloc, score
      68)
  - id: f2916ca04ff2
    note: Senior/Lead Product Manager @ Streem Energy (reloc, score 62)
  - id: c50fa5dfab4b
    note: Product Manager @ Streem Energy (reloc, score 48)
  - id: f475f9d8c872
    note: Product Manager H/F - CDI @ Converteo (reloc, score 62)
  - id: 3ea6edede87e
    note: Product Manager (F/H) @ Roole (reloc, score 42)
  - id: aa9d6202dcc1
    note: Head Of Product (H/F) @Chargemap @ Groupe Brakson (Chargemap, Mister EV,
      Saabre) (reloc, score 58)
  - id: 53b0adb071c0
    note: Product Manager Business Intelligence @ Flexcity by Veolia (reloc, score
      68)
  - id: 90659ee18c33
    note: Product Manager Sportsbook Platform F/M @ Betclic Group (reloc, score 42)
  - id: 3b26e26523da
    note: Technical Product Manager  (m/f/x)- Plat @ Dynatrace (reloc, score 62)
  - id: 6b9af3529701
    note: Head of Product - CRM Vertical @ Zeffy (reloc, score 52)
  - id: a0a087a21184
    note: Product Manager @ Wooclap (reloc, score 58)
  - id: 9e262736af7f
    note: CDI - Make Up Senior Product Manager - H @ Groupe Clarins (reloc, score
      28)
  - id: c3c704544c29
    note: Technical Product Manager @ LEFTY (reloc, score 58)
  - id: e67bc1edb5cc
    note: Senior Product Manager (Accounts Receiva @ Quadient (reloc, score 58)
  - id: 541c95f3a983
    note: Product Manager (SaaS) @ LEFTY (reloc, score 48)
  - id: 9f7427a871cb
    note: Product Manager @ Riot (reloc, score 42)
  - id: 7f68a69488ec
    note: Senior Product Manager @ Dotfile (reloc, score 58)
  - id: 1f3287b44bf1
    note: Senior Product Manager @ Kiro (reloc, score 42)
  - id: 4419467b0de3
    note: Experienced Entrepreneurial Product Lead @ Dynatrace (reloc, score 58)
  - id: f0e4f43e9939
    note: Consultant.e Product Manager Tech @ IKXO (reloc, score 52)
  - id: c7f79ce2ddbd
    note: Consultant.e Product Manager E-commerce @ IKXO (reloc, score 38)
  - id: 79831cedebe7
    note: Consultant.e Product Manager App Mobile @ IKXO (reloc, score 42)
  - id: 9e55302595be
    note: Consultant.e Product Manager Senior @ IKXO (reloc, score 48)
  - id: a4c657a0cda3
    note: Senior Product Manager Skills - CDI - Ly @ 365Talents (reloc, score 48)
  - id: 416448354ddf
    note: Senior Product Manager (H/F) @ Koralplay (reloc, score 62)
  - id: 739b1a6ae444
    note: Product Manager - CDI - Paris @ Orus (reloc, score 52)
  - id: f34049b70882
    note: Lead Product Manager (h/f/nb) - CDI @ Kiabi (reloc, score 48)
  - id: 8f248bcc192b
    note: Product Manager @ Daveo (reloc, score 42)
  - id: cfccaefe25e9
    note: Product Owner / Product Manager IA (H/F) @ Monsieur Guiz (reloc, score 62)
  - id: 51e5af9452b3
    note: Product Manager @ Upway (reloc, score 42)
  - id: 4cd289b6fc2d
    note: Product Manager - Plateformes & IA F/H @ KPMG France (reloc, score 68)
  - id: 10c4aa66c0e3
    note: VP Product Marketplace Platform @ Mirakl (reloc, score 62)
  - id: 3e82575f6048
    note: Product manager @ sosa ingredients (reloc, score 32)
  titles: []
