searches:
- term: Senior Product Manager data
  location: Spain
  sites:
  - indeed
  - google
  results_wanted: 20
  hours_old: 72
- term: Senior Product Manager ai_ml
  location: Spain
  sites:
  - indeed
  - google
  results_wanted: 20
  hours_old: 72
- term: Senior Product Manager AdTech advertising
  location: Spain
  sites:
  - indeed
  - google
  results_wanted: 20
  hours_old: 72
- term: Senior Product Manager remote
  location: Spain
  sites:
  - linkedin
  results_wanted: 15
  hours_old: 72
- term: Senior Product Manager data
  location: ''
  sites:
  - linkedin
  results_wanted: 10
  hours_old: 72
- term: Principal Product Manager remote
  location: Spain
  sites:
  - linkedin
  results_wanted: 15
  hours_old: 72
- term: Senior Product Manager snowplow
  location: Spain
  sites:
  - linkedin
  results_wanted: 15
  hours_old: 72
is_remote: true
