searches:
- term: Principal Product Manager data
  location: France
  sites:
  - indeed
  - google
  results_wanted: 20
  hours_old: 72
- term: Principal Product Manager ML AI
  location: France
  sites:
  - indeed
  - google
  results_wanted: 20
  hours_old: 72
- term: Principal Product Manager remote
  location: France
  sites:
  - linkedin
  results_wanted: 15
  hours_old: 72
- term: Principal Product Manager data
  location: ''
  sites:
  - linkedin
  results_wanted: 10
  hours_old: 72
- term: Principal Product Manager python
  location: France
  sites:
  - linkedin
  results_wanted: 15
  hours_old: 72
is_remote: true
